spring.application.name=youtubeminer
server.port=8083
videominer.base.url=http://localhost:8080/videominer/api

youtubeminer.baseuri=https://youtubeminer.tv/api/v1

youtubeminer.maxVideos = 10
youtubeminer.maxComments = 10

videominer.uri=http://localhost:8080/videominer/channels

youtube.api.key=AIzaSyALcHjDFxP770OSLGrgo47mMpEj6hczf6A
